# General
SAGEMAKER_ROLE = 'TODO'
S3_MODEL_DATA_BUCKET = "TODO"
# Note: serverless deployment does not need a instance type
SAGEMAKER_INSTANCE_TYPE = "ml.c4.xlarge"
S3_ROOT_DIR = "TORCHMAKER"

# CIFAR Model
TRAIN_CIFAR_BATCH_SIZE=8
TRAIN_CIFAR_EPOCHS=4
SAGEMAKER_CIFAR_SERVERLESS = True
SAGEMAKER_CIFAR_ENDPOINT_NAME = "cifar-model"
S3_CIFAR_MODEL_DATA_KEY = f"{S3_ROOT_DIR}/cifar/model.tar.gz"
S3_CIFAR_MODEL_DATA_PATH = f"s3://{S3_MODEL_DATA_BUCKET}/{S3_CIFAR_MODEL_DATA_KEY}"

# ROBERTA Model
SAGEMAKER_ROBERTA_SERVERLESS = True
SAGEMAKER_ROBERTA_ENDPOINT_NAME = "roberta-model"
S3_ROBERTA_MODEL_DATA_KEY = f"{S3_ROOT_DIR}/roberta/model.tar.gz"
S3_ROBERTA_MODEL_DATA_PATH = f"s3://{S3_MODEL_DATA_BUCKET}/{S3_ROBERTA_MODEL_DATA_KEY}"

